### ISSUE TITLE
API Team Abfrage

### ISSUE THREAD

**Issue by Bisota** [api-fussball/api-dart#1]
Hi zusammen,

ich habe gerade die API mit verschiedenen Abfragen getestet. Die Beispielabfrage für einzelne Teams gibt eine Fehlermeldung zurück.

Die Abfrage in Postman:
curl --location 'https://api-fussball.de/api/team/011MI8V6UC000000VTVG0001VTR8C1K7' \
--header 'x-auth-token: xxxxxxx'

Es kommt folgende Fehlermeldung zurück:
{
    "success": false,
    "data": [],
    "message": "PathNotFoundException: Cannot open file, path = '/srv/football-api/dart-api/fonts/150yjhkw.ttx' (OS Error: No such file or directory, errno = 2)"
}

Den Token, den ich verwende, funktioniert einwandfrei bei der Club Abfrage. Mit error number = 2 scheint die Abfrage soweit auch korrekt zu sein.

**Comment by wesolowski** [comment]
Hi, 

danke für die Meldung dieses Fehlers. 
Bei unserem Server gab es ein Problem, es wurde bereits behoben. 
Jetzt sollte alles einwandfrei funktionieren.
